apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator-deployment
  namespace: monitoringstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
      - name: load-generator
        image: localhost:32000/load-generator   # Replace with your registry/image
        env:
        - name: TARGET
          value: "http://192.168.0.100:30000/primecheck"
        - name: FREQUENCY
          value: "10"
